// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARQF6LKPqOCcZEzcZxqifwmAHt4Nt9Rw',
    appId: '1:947461311190:web:20bd47933a05077fecd777',
    messagingSenderId: '947461311190',
    projectId: 'myproject-c77e8',
    authDomain: 'myproject-c77e8.firebaseapp.com',
    storageBucket: 'myproject-c77e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7tYIXWAzF7gSv-aVnCfk0YoTmrwiFpE',
    appId: '1:947461311190:android:eba57831bf52f24decd777',
    messagingSenderId: '947461311190',
    projectId: 'myproject-c77e8',
    storageBucket: 'myproject-c77e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2RdmO9xTHa1b__dahdzdyeB1I5W2xWSQ',
    appId: '1:947461311190:ios:1c00f1dcfcd54f1fecd777',
    messagingSenderId: '947461311190',
    projectId: 'myproject-c77e8',
    storageBucket: 'myproject-c77e8.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2RdmO9xTHa1b__dahdzdyeB1I5W2xWSQ',
    appId: '1:947461311190:ios:1c00f1dcfcd54f1fecd777',
    messagingSenderId: '947461311190',
    projectId: 'myproject-c77e8',
    storageBucket: 'myproject-c77e8.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDARQF6LKPqOCcZEzcZxqifwmAHt4Nt9Rw',
    appId: '1:947461311190:web:c5fa1a2c068f0b73ecd777',
    messagingSenderId: '947461311190',
    projectId: 'myproject-c77e8',
    authDomain: 'myproject-c77e8.firebaseapp.com',
    storageBucket: 'myproject-c77e8.firebasestorage.app',
  );
}
